### ISSUE TITLE
[Spell] Auto Shot Issue

### ISSUE THREAD

**Issue by Ahmpy** [Atlantiss/NetherwingBugtracker#135]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Auto Shot is incorrectly being stalled by casting spells
**Current behaviour**:
When one casts a spell such as Hunter's Mark, or Mend Pet, even racials such as Berserking, and then tries to auto attack, it is significantly delayed. What happens is the auto shot is being charged up as it should but never fires unless I stop casting spells. I'm not sure whether casting a spell is delaying the shot by the bow's weapon speed, or if the shot is being delayed by GCD+.5s wind up time

Ex: I target a mob and hunter's mark, immediately followed by pressing auto shot. Now that auto shot is engaged, nothing happens. 1.5s  later on next GCD I cast berserking, still no auto shot. Finally about 2s later, the bow shoots after over 3 seconds of being engaged, and after I stop using spells.

edit: https://youtu.be/jejtpt_AEK8
Here is a video of how the current behavior on beta revision 2124 looks like when you cast spells or use potions as a hunter. Auto shot is toggled and continuously gets reset whenever a spell is cast.

**Expected behaviour**: 
What should happen is the auto shot should fire after a .5s wind up time, and should not be impacted by casting any spells beforehand. 

edit: https://youtu.be/HpLxEx8OfUk?t=197
This video shows a hunter casting a hunter's mark, which does not interrupt his spells, immediately followed by a bestial wrath and a mana potion which also do not interfere with his auto shot timer.

**Server Revision**: 
**2124**

**Comment by greath2217** [comment]
you closed my ticked "Hunter instant cast stuck while running #355" and marked it as a duplicate of this one here. but after reading this treath it doesnt seem to be the same thing at all. he is talking about auto shot beeing delayed. that has nothing to do with not beeing able to cast instand casts like arcane shot while running...

**Comment by Gniddikon** [comment]
I feel like this was fixed with one of the fixes yesterday. I am now able to run away from a mob and use all instant casts flawlessly. Can other hunters confirm?

**Comment by shengo8** [comment]
Can confirm this is also affecting the shoot skill for wands. Tried using berserking and shooting with my wand, get one shot then the auto-shooting is cancelled.

**Comment by Easyfraggy** [comment]
If you have some new info as to why this was reopened please share? I don't have this problem anymore.

**Comment by Gniddikon** [comment]
Same, haven’t had the issue at all since the fix. Could you elaborate when it happens?

**Comment by Ahmpy** [comment]
Yeah this was re-opened because i accidentally closed it - it was not closed by an admin. Also this has never been fixed, and remains a problem. Gniddikon the issue you're talking about is completely different. Easy fraggy i posted a video of it and it is very much a problem still

**Comment by Easyfraggy** [comment]
Yeah nice the video shows its a different issue than I was thinking of. Still broken idd.

**Comment by Wolffenstein** [comment]
Fixed in rev 2153.
