### ISSUE TITLE
[Megathread][Quest][NPC] Stratholme

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#1960]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

Unsure how to do this megathread, but here is a copy/paste from my notepad.

conjuror stratholme no water elementals (**FIXED**)
unforgiven not spawned - **supposed to be spawned all the time, but invisible. Once you go near his spawnpoint, then he should spawn.**

timmy doesnt spawn - **He should spawn after we've cleared the outside area of the chapel.** 

2 hammersmiths - **should only spawn when picking up blacksmithing plans**

cannon master willey completely bugged scriptwise, like :toto: - **The cannons don't work, the riflemen just stands in the middle of the corridor between the cannons and the start of the corridor. They should be shooting us from max range and then gun us down, where we blow them up with the cannons, but they don't work.**

the scarlet bastion - sorcerer fire blast 1000 dmg, unsure about this - **but it seems like it deals too much damage.**

Barthillas usually stands outside the chapel next to aurius, once you go inside his radius (the entire area), he should run immediately to the furthest gate away that leads to the ziggurats. 

black guard swordsmith pre summoned in a wrong place. same as hammersmith - Spawns when looted the blacksmith plans on the ground.

baroness anastari no mind control - self-explanatory.

ramstein the gorger no cool intro once we kill all his buddies. no dialogue too

Baron rivendare room doesnt close door when we go in - selfexplanatory.

skeletons spawn very late - boss fight vs baron rivendare.

Black Guard Sentry doesn't spawn after kill ramstein and the mindless mobs - should spawn 20 seconds after we kill ramstein the gorger.

The Restless Souls and The Great Fras Siabi bugged - questwise, no credits given for sucking the ghosts, the great fras siabi, NPC isn't spawned.

**Comment by ttghnw** [comment]
Lul Scholomance - fix title to Stratholme :) also devs will prolly ask one ticket per issue.

**Comment by Evolvee** [comment]
some of it fixed in rev yummy

**Comment by Mewmewww** [comment]
> Lul Scholomance - fix title to Stratholme :) also devs will prolly ask one ticket per issue.

Ah, sorry it was stratholme! But kutsal said a megathread in this case is better :)

**Comment by Easyfraggy** [comment]
The more details you give the easier it is to fix. This is very badly detailed and I had to answer 10 questions about how it should work before Evolve could fix the ziggurats. Please make a more detailed report on the remaining issues.

**Comment by Mewmewww** [comment]
> The more details you give the easier it is to fix. This is very badly detailed and I had to answer 10 questions about how it should work before Evolve could fix the ziggurats. Please make a more detailed report on the remaining issues.

Sorry, Easy. I've now given a description on how they should work.

**Comment by Ashfall7x** [comment]
- Mailboxes do not spawn any mob. 
- Fras Siabi mailbox key does not drop.
- Dying after Rammstein the Gorger resets the instance (?)
- Some bosses like Timmy, Unforgiven do not exist.
- Scarlet Commander does not successfully transform into a Dreadlord, name doesn't change and still stays as a humanoid.
- Egan's quest does not work, you blast the spectral citizens and they get freed but quest does not count.
- "Iron Gates falling down to trap you with rats" event does not occur.
- Banshee Boss (forgot her name, the Ziggurat before Baron) does not possess any player.

These are issues I encountered just yesterday, wanted to let you guys know what is fixed and what isn't.

**Comment by 0vertime** [comment]
Baron door did not open after killing the aoe skeletons.

**Comment by Homiecup** [comment]
> 2 hammersmiths - **should only spawn when picking up blacksmithing plans**
> 
> black guard swordsmith pre summoned in a wrong place. same as hammersmith - Spawns when looted the blacksmith plans on the ground.

https://wowwiki.fandom.com/wiki/Blacksmithing_Plans
https://wowwiki.fandom.com/wiki/Black_Guard_Swordsmith

Can confirm that it should be this way.

**Comment by Homiecup** [comment]
Timmy the cruel doesn't currently spawn, but is supposed to spawn when you have cleared all the mobs in the courtyard outside of the scarlet bastion.
https://wowwiki.fandom.com/wiki/Timmy_the_Cruel
https://youtu.be/RmMI-abhyi8?t=385

The unforgiven doesn't spawn either and is supposed to spawn once you walk past an archway close to the rat gate. He spawns together with 3 other copies of himself that are non elite.
https://wow.gamepedia.com/The_Unforgiven

Postmaster is a "summoned" boss that is supposed to spawn as you open 3 of the 6 mailboxes in the dungeon. He spawns together with 3 elite undead postman mobs.
https://wowwiki.fandom.com/wiki/Postmaster_Malown
https://wowwiki.fandom.com/wiki/Undead_Postman

Skul is a rare that doesn't spawn currently, it can spawn near the stratholme courier and fras siabi or in the festival lane area right by a Hearthsinger Forresten spawn.
https://wowwiki.fandom.com/wiki/Skul

**Comment by Krotsker** [comment]
Can confirm as of 16/10/19 Timmy the Cruel still doesnt spawn after clearing the courtyard

**Comment by Wolffenstein** [comment]
Fixed in rev 3783.
