### ISSUE TITLE
[Class]Mage Talent Elemental Precision should give 6% hit to Frostbolt

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#2556]
During retail TBC a bug existed for the entire expansion (it was not fixed until WotlK) where the talent Elemental Precision (3% spell hit for Frost + Fire spells) was actually giving 6% spell hit to Frostbolt- it was theorized that this was due to the binary/nonbinary spell system.

**Sources**

Elitist Jerks

> I'll indulge your query because the actual testing of the EP bug is lost somewhere deep in an old thread we don't use any more and a pig to find.
> 
> Back then, it was detected on WoW forums that some chap who had raided frost (which was really bad at the time) for months had logs of thousands of Bolts, recording between 0.9 and 1.3% resist at any hit value beyond 130ish.
> 
> There were the following possible scenaria:
> 
> 1) Emp Fbolt was giving 5%
> 2) Binary effect was interfering with "innate boss resilience" and cancelling the partial resist along side 5% of the hit
> 3) EP was giving it's old 2% per point benefit to Fbolt or
> 4) WC was supplying 5%
> 
> We all speculated and did minor-size sampling, which was all moot, because nothing lvl 73 stood still and ate bolts long enough, we didn't want to raid Frost, and even if we did we didn't want to risk sucking balls with 4% miss rate. Not to mention Dr. Boom was too low level. Until some God-sent man, copied a lvl 65 mage to PTR, chugged some mp5 elixirs, and came up with a dozen Parsings showing:
> 
> 1) WC gave 0% hit.
> 2) Emp Bolt gave 0% hit.
> 3) 3 points in EP gave 6% hit.
> 4) All of the Above gave 6% hit.
> 
> Each test cycle was in the region of 600-700 frostbolts and the discrepancy from assumed value was to the tune of 0.5%. This was the last chapter in determining the Frostbolt bug.
> 
> This is irrefutable evidence (1) EP is giving 6% instead of 3% (2) it is 6% and not 5% (3) No other talent has anything to do with it.
> 
> There is no reason to wear more than 125hit as frost, assuming no dranei in group, no ToW in group and 3/3 EP. Period. This is one of the most well-established data-researching efforts we've seen, outside of raid-data on EJ.
> 
> Edit: As a side-note, in future, if you do intend to turn up with artefacts about anything, please note:
> 
> (not specifically aimed at you, Max)
> 1) Sample sizes of less than 500 samples are ridiculously prone to dilution/spikes/flukes. Trying to determine a 1% miss, when 1% represents "two frostbolts" is idiotic statistics. So is assuming "1% = 1 in 100", it shows statistical ignorance.
> 2) 5-man data is irrelevant; mobs that are not 73 do not have 17% innate resist rate. It can also be argued that 73 mobs that aren't bosses may also provide wrong results, because they don't include innate boss resilience, which may or may not affect the tests.
> 3) Samples in a non-controlled environment are extremely bad value; if you do a run where a mob is Banished or switches on CloS, or Spell Reflect, or Reflect Shield, depending on which damage meter you use you'll record a possible resist when it isn't due to your miss rate. The same is true of being Mind Controlled and attacking your own team-mates , who may also resist.

http://web.archive.org/web/20080811105543/http://elitistjerks.com/f31/t18441-mage_sweet_informational_thread/p42/

> Frostbolt gains an additional 1% hit per a point in Elemental Precision

http://web.archive.org/web/20080913120526/http://elitistjerks.com:80/f31/t18441-mage_sweet_informational_thread/

Forum post discussing the Elemental Precision (Ghost Hit) bug still existing at the start of WotlK:

> at 80 i would stay as frost to do dungeons and heroics until you get all lvl 80 blues+ i would reccomending having a nice balance of crit and haste. haste will be worth more, but spell power is worth about 1.5x crit or haste. the elemental precision bug still exists (and works with frostfirebolt), so you get 6% hit from EP with your frost spells only (your fire spells only get 3% with the ep bug).

http://www.clanyawa.com/viewtopic.php?t=5558

TBC Wowhead Comments discussing Ghost Hit: https://www.wowhead.com/forums&topic=19679

Wowwiki discussing Frost "ghost hit": http://wowwiki.wikia.com/wiki/Talk:Spell_hit

TBC Mage Karazhan Guide discussing ghost hit: https://frostisthenewblack.wordpress.com/2008/09/17/spell-hit-your-way-into-karazhan/

**Comment by Easyfraggy** [comment]
Nice to see a lot of links for proof on reintroducing a bug - Like with Seal Twisting - because they existed for entire expansion I believe this should also be reintroduced.

**Comment by Dekirayne** [comment]
Great post. Since it was a thing during the whole expansion I would expect for it to be a part of this server aswell.

**Comment by Dekirayne** [comment]
if this is not implemented it will heavily hit the arcane mages because they have on lower spellhit need for arcane blast and having more spellhit on frostbolt makes them compensate for gear lacking spellhit, because in arcane mages use frostbolt a lot when not in arcane burn phase.

**Comment by Wolffenstein** [comment]
Fixed in rev 2477.

**Comment by Evolvee** [comment]
There is a difference between seal twisting which is a subproduct of a bigger mechanic and flat out completely bugged talent that should not behave like that. If we are reintroducing all bugs, no matter what they were caused by, I would like you to reintroduce my bugs as well, lets start with this one:  https://github.com/Schaka/TBC-research/issues/5

thanks in advance

**Comment by ircfelix** [comment]
According to @Easyfraggy, the talent currently only gives 3% instead of 6% hit to frostbolt, so the fix did not work.

> The first test I did with 1354 frostbolts above was with the talent only - shows that the talent only
> gives 3% hit. Feel free to use that in the correct bug report.

> _Originally posted by @Easyfraggy in https://github.com/Atlantiss/NetherwingBugtracker/issues/5013#issuecomment-486525985_

**Comment by netherspite** [comment]
> .

This 'bug' was affecting the whole mage specs balance, specifically making arcane/frost 40/0/21 with frostbolt as a nuke viable until ~t6.
Blizzard never bothered to fix it, probably to keep the spec balance as is and not to nerf Frost even further in PvE.
If the server is blizzlike the class balance should be exactly the same and this 'bug' should be reintroduced as well.

**Comment by Wolffenstein** [comment]
Fixed in rev 3039.

**Comment by netherspite** [comment]
So I did some experiments today and used a gear combination giving about 7% extra spell hit chance in our Kara run today.
We had an ele shaman in my group and I have 3/3 Elemental Precision talent.
I was taking screenshots of all attempts on all bosses where I was using this gear combination.

In total I have the following numbers:
92+65+20+120+153+42+127+85 = 704 frostbolt casts
2+8+2+6+10+7+11+4 = 50 of them were fully resisted
50 / 704 = ~7.1% resists
Theoretical value should be 17% - 6% - 3% - 7% = ~1% resists
So I've got as many resists as if I wouldn't have Elemental Precision talent at all, which is weird.
Our last fight I switched back to 13% spell hit gear (and we've lost our ele shaman) the resists went back to normal (1-2%)

While this amount of casts is not big enough to reduce the standard deviation below 1%, it's still highly unlikely to see 7.1% resists where there should be 1% on 704 casts.

I believe that the ghost hit is still not working correctly. Please verify it in some real test on raid bosses.
As much as I would do it myself with like 5k+ casts I cannot do so because that would require me to raid with that gear combination for a week or two and that wouldn't be very nice to my guild.

**Comment by netherspite** [comment]
Attaching screenshots with those values I've mentioned:

Illhoof:

![WoWScrnShot_062919_105127](https://user-images.githubusercontent.com/5777848/60383420-952e6e80-9a9a-11e9-8b67-8b3f3c8022cc.jpg)

Netherspite

![WoWScrnShot_062919_113519](https://user-images.githubusercontent.com/5777848/60383421-952e6e80-9a9a-11e9-84a4-fcfefd71fd1e.jpg)
![WoWScrnShot_062919_113532](https://user-images.githubusercontent.com/5777848/60383422-952e6e80-9a9a-11e9-8fc0-b2db8649bcce.jpg)

Prince

![WoWScrnShot_062919_115221](https://user-images.githubusercontent.com/5777848/60383423-95c70500-9a9a-11e9-9726-2d0c6f35202b.jpg)

Nightbane 

![WoWScrnShot_062919_124627](https://user-images.githubusercontent.com/5777848/60383424-95c70500-9a9a-11e9-8870-9d94f3793bc1.jpg)
![WoWScrnShot_062919_124637](https://user-images.githubusercontent.com/5777848/60383426-95c70500-9a9a-11e9-9ff8-446f4f0394d9.jpg)
![WoWScrnShot_062919_124643](https://user-images.githubusercontent.com/5777848/60383427-965f9b80-9a9a-11e9-84df-67ccd3c44bb8.jpg)
![WoWScrnShot_062919_124648](https://user-images.githubusercontent.com/5777848/60383428-965f9b80-9a9a-11e9-8cb5-72e16e30c49d.jpg)

**Comment by viktor-wolf** [comment]
I can confirm this still doesn't give 6% hit - I just did Gruul with 11% hit (5% from gear, 6% from this, technically) and I had 13.2% resist rate on FB.

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.
