### ISSUE TITLE
[Loot] Sunscale Feathers do not drop after 1st use on any nest

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#376]
**Description**:
I got 1st [Sunscale Feather](http://web.archive.org/web/20100808064446/http://thottbot.com:80/i5165) pretty fast and used it on Yellow Nest. After that it never dropped again. 
I know that feathers usually on pservers do not drop if you already have one in bags.
Overall I killed 200 Sunscale Scytheclaws (almost exclusively for that quest, maybe -20 before accepting quest), was able to loot 60 and got only 1 initial feather.
After retaking 1st time I got one feather from 3rd Scytheclaw, used it on Red Nest and they stopped dropping again.
After retaking 2nd time and not using feathers on nests I was able to farm 3 in 10 minutes.

**Current behaviour**:
Sunscale feathers do not drop after using 1st one on any nest.

**Expected behaviour**: 
[Sunscale Feather](http://web.archive.org/web/20100808064446/http://thottbot.com:80/i5165) drop should not depend on having them in bags or using on the nests.

**Server Revision**: 2040

**Comment by GetoBoyz** [comment]
I will second this issue. Got 2 while at the Raptor Grounds doing the quest Stolen Silver. Went to the nests and used both of them, and after approximately 100 Sunscale Scytheclaws later had no luck. Abandoned the quest and retook it. By my third Scytheclaw kill I had a feather. At this stage currently, will kill ~30 raptors and report back.

**Comment by Jezofine** [comment]
Maybe game thinks that you completed whole quest because of 1 completed objective.

**Comment by wtRCH** [comment]
@pelekon

**Comment by pelekon** [comment]
fixed in rev 2561

**Comment by RelmAtlantiss** [comment]
If you use a feather on the nest, you can't loot a feather again.
Still bugged in rev 2603

**Comment by aresbrutus** [comment]
Please try to delete your cache and try if that helps.

**Comment by mhawkins30** [comment]
Can confirm this issue persists as of rev 2712. I got two feathers fairly quickly and used them on the red and yellow nests. After that, I killed about 60 more sunscale scytheclaws and didn't get a single other feather. Then I abandoned the quest and restarted and I got 3 feathers within about 10 kills, without using a feather on any nests.

**Comment by mhawkins30** [comment]
Also, at one point while the quest was in a bugged state, I was grouped with someone who was also on the quest but hadn't used any feathers on nests, and while feathers dropped for them, the shared quest loot system didn't give me any from the same corpse.

**Comment by Manaci** [comment]
[Fixed](https://github.com/Atlantiss/NetherwingBugtracker/issues/3866)
