### ISSUE TITLE
The Big Vanilla Quest Fixing Post

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#5473]
As of now, I have done 99.9% of every single HORDE or shared quest in the game that I can. 
So now I'm standing left with a bunch of bugged, disabled and wrongly enabled quests that I would like to get fixed. 

**Part 1: Bugged Quests**
_PvE Section_
[The Restless Souls](https://db.excalibur.ws/?quest=5282) (ID 5282)
This quest require you to bring [Egan's Blaster](https://db.excalibur.ws/?item=13289) to Stratholme and shoot either [Ghostly Citizens](https://db.excalibur.ws/?npc=10385) or [Spectral Citizens](https://db.excalibur.ws/?npc=10384). Currently when shooting said NPCs, they do turn into [Restless Souls](https://db.excalibur.ws/?npc=11122) but these don't automatically turn into [Freed Souls](https://db.excalibur.ws/?npc=11136) which makes this quest impossible to complete.

[The Great Fras Siabi](https://db.excalibur.ws/?quest=5214) (ID 5214)
This Quest requires you to go to the [Fras Siabi's Premium Tobacco](https://db.excalibur.ws/?object=175484) container, open it and then fight the summoned [Fras Siabi](https://db.excalibur.ws/?npc=11058) to loot the item [Siabi's Premium Tobacco](https://db.excalibur.ws/?item=13172) from him. Currently the container can't be interacted with so the boss can't be summoned, simple as that.

[The Battle of Darrowshire](https://github.com/Atlantiss/NetherwingBugtracker/issues/1279) and its followup. Already reported so I won't dwell into this one further, deemed low prio sadly. 

~~[The Madness Within](https://db.excalibur.ws/?quest=7461) (ID 7461) and its followup.
When you kill [Immol'thar](https://db.excalibur.ws/?npc=11496), [Prince Tortheldrin](https://db.excalibur.ws/?npc=11486) does not become hostile rendering this quest impossible to complete. This will quickly delve into the Dire Maul (East, West and North) situation of the whole area being in a super screwed up state of random npc placement and just everything seems off in there (this is the only quest you can't complete though except for some DM North Tribute stuff). This probably won't get looked at until most of Dire Maul is swiped clean and rewritten.~~

_PvP Section_
This one mostly focuses on Alterac Valley since that place is kinda screwed up too, but the quest part should be easy to fix (except for missing NPCs and their repeatable quests that I really won't delve into here cause that would just bloat it up). 
These quests all involve capturing a specific point in AV, so for Horde there's [Capture a Mine](https://db.excalibur.ws/?quest=7124) (ID 7124), [Assault a Graveyard](https://db.excalibur.ws/?quest=7082) (ID 7082) and [Destroy a Bunker/Tower](https://db.excalibur.ws/?quest=7101) (ID 7101).
Alliance counterparts are [Capture a Mine](https://db.excalibur.ws/?quest=7122) (ID 7122), [Assault a Graveyard](https://db.excalibur.ws/?quest=7081) (ID 7081) and [Destroy a Bunker/Tower](https://db.excalibur.ws/?quest=7102) (ID 7102).
These quests are currently not giving said credit when the objectives are either captured or destroyed, which should be the job of the [Mine Credit Marker](https://db.excalibur.ws/?npc=13796), [Graveyard Credit Marker](https://db.excalibur.ws/?npc=13756) and [Tower Credit Marker](https://db.excalibur.ws/?npc=13778)

~~This is also the case with the Arathi Basin quest [The Battle For Arathi Basin!](https://db.excalibur.ws/?quest=8120) (ID 8120) (and the lower level versions of it)
Alliance counterpart being [The Battle For Arathi Basin!](https://db.excalibur.ws/?quest=8105) (ID 8105) (and also the lower level versions of it)
Here it's the same problem, with the [Mine Credit Marker](https://db.excalibur.ws/?npc=15005), [Lumber Mill Credit Marker](https://db.excalibur.ws/?npc=15004), [Blacksmith Credit Marker](https://db.excalibur.ws/?npc=15002), [Farm Credit Marker](https://db.excalibur.ws/?npc=15003) and [Stable Credit Marker](https://db.excalibur.ws/?npc=15001) not working correctly making the quest impossible to complete~~

**Part 2: Wrongfully Enabled and Disabled Quests**
_PvE Section_
In Light's Hope there's the [Quartermaster Miranda Breechlock <The Argent Dawn>](https://db.excalibur.ws/?npc=11536#starts) who gives out a quest for either Superior or Epic items requiring Argent Dawn tokens. This quest gets its requirements lowered based on the reputation level of the player, best discount at Exalted. Currently the Epic version [Epic Armaments of Battle - Exalted Amongst the Dawn](https://db.excalibur.ws/?quest=9228) and the Revered, Honored and Friendly version is in-game but strangely enough the Superior version is not. 
So the following quests need to be enabled: [Exalted](https://db.excalibur.ws/?quest=9227) (ID 9227), [Revered](https://db.excalibur.ws/?quest=9226) (ID 9226), [Honored](https://db.excalibur.ws/?quest=9223) (ID 9223), [Friendly](https://db.excalibur.ws/?quest=9221) (ID 9221) (the reputation factor should work accordingly already as seen by the Epic version)

Next up is the SIlithus summoning quests, which right now are semi-enabled. You can make the summoning items but only ONCE, since the repeatable quests are all locked. The Revered and above chain also isn't enabled.
So first off, [Abyssal Crests](https://db.excalibur.ws/?quest=8362) (ID 8362), [Medallion of the Station](https://db.excalibur.ws/?quest=8333) (ID 8333), [Abyssal Signets](https://db.excalibur.ws/?quest=8363) (ID 8363) and [A Humble Offering](https://db.excalibur.ws/?quest=9248) (ID 9248) are not enabled while they should.
Then when a player gets Revered or above, the following quest chain is enabled [Goldleaf's Discovery](https://db.excalibur.ws/?quest=8343) (ID 8343) --> [Lord's of the Council](https://db.excalibur.ws/?quest=8341) (ID 8341) which opens the repeatable quest [twilight Ring of Lordship](https://db.excalibur.ws/?quest=8342) (ID 8342) and continues into [Bor Wishes to Speak](https://db.excalibur.ws/?quest=8351) (ID 8351) --> [Scepter of the Council](https://db.excalibur.ws/?quest=8352) (ID 8352) which at the end opens up the repeatable quest [Abyssal Scepters](https://db.excalibur.ws/?quest=8364) (ID 8364)

(All IDs together to be **ENABLED** - 9227, 9226, 9223, 9221, 8362, 8333, 8363, 9248, 8343, 8341, 8342, 8351, 8352, 8364)

~~_PvP Section_
Currently there are some old PvP quests in-game that on retail was removed from Alterac Valley in 1.10 [Proof](https://wowwiki.fandom.com/wiki/Patch_1.10.0) (under Alterac Valley Section) _"Players in Alterac Valley will no longer drop Darkspear Troll Mojo, Dwarf Spines, Forsaken Hearts, Human Bone Chips, Orc Teeth, etc. and the quests have been removed for these items. Instead when a player is slain in Alterac Valley, any enemies that were in that player's threat list will gain 1 point of reputation with either the Frostwolf or Stormpike factions."_
Since the items are not on the drop-table of the insignia looting(which is screwed up too, giving specific Ally items to horde players and not the specific horde items, not flesh drops etc, that's for another AV time)
Since I play Horde, you can currently take 3 of the 4 old PvP quests (1 NPC is not in his tower anymore so can't take that and one of the 3 quest's hand-in NPC is not that but you take it from a wanted poster) I'll just post all of them to be sure.
So anyways, the following quests need to be DISABLED
[Ally of the Tauren](https://db.excalibur.ws/?quest=7362) (ID 7362), [Wanted: DWARFES!](https://db.excalibur.ws/?quest=7401) (ID 7401), [Favor Amongst the Darkspear](https://db.excalibur.ws/?quest=7361) (ID 7361), [The Human Condition](https://db.excalibur.ws/?quest=7363) (ID 7363), [The Archbishop's Mercy](https://db.excalibur.ws/?quest=7366) (ID 7366), [Gnomeregan Bounty](https://db.excalibur.ws/?quest=7364) (ID 7364), [Staghelm's Requim](https://db.excalibur.ws/?quest=7365) (ID 7365) and [Wanted: Orcs!](https://db.excalibur.ws/?quest=7402) (ID 7402)~~

~~(All IDs together to be **DISABLED** - 7362, 7401, 7361, 7363, 7366, 7364, 7365, 7402)~~

**Server Revision**: 
2898 (when 1st posted), 3174 (on last edit)

**Comment by Evolvee** [comment]
great report 👍

**Comment by Evolvee** [comment]
disabled 7362, 7401, 7361, 7363, 7366, 7364, 7365, 7402 in 2914

**Comment by thestranger064** [comment]
The pvp section her is still not working and giving credits.

Capture a Mine
The graveyards of Alterac 
Towers and Bunkers

**Comment by Manaci** [comment]
@thestranger064 yup, most of this has still not been fixed unfortunately.

**Comment by Manaci** [comment]
Edited to reflect recent fixes

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/69008775-992a3280-094e-11ea-950a-fa0d8ddbc864.png)
fixed

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/69009109-a9dca780-0952-11ea-9295-ad2e99efca8d.png)
 fixed

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/69009303-6420de80-0954-11ea-9721-e31f2a03ba8d.png)
 fixed

**Comment by Evolvee** [comment]
@Manaci Correct me if am wrong, this entire thread is fixed except Battle for Darrowshire? if thats the case, close it as its reported separately somewhere else already

**Comment by GMThunderan** [comment]
[The Great Fras Siabi](http://db.excalibur.ws/?quest=5214) is broken again. Tested it on PTR. When I try to summon the NPC, nothing happens. Furthermore [The Unforgiven](http://db.excalibur.ws/?npc=10516) is still missing.
