### ISSUE TITLE
[Spell][Hunter] Aspect of the Viper is orders of magnitude more effective than it should be

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#7566]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://wow.gamepedia.com/index.php?title=Aspect_of_the_Viper&direction=prev&oldid=1458832
> The effectiveness of the spell changes with the hunter's current mana. With at least 90% mana, the effect is 11% of total Intellect. This is followed by a linear increase up to 55% of total Intellect until the mana bar is down to 20%. The base effect **can never be higher than 55% or lower than 11% of total Intellect unless the Gronnstalker set bonus is applied.**
> The exact formula for the scaling appears to be:
> `MP5Viper = Intellect × 22/35 × ( 0.9 - Manacurrent / Manamax ) + Intellect × 0.11`
> with a lower cap of `Intellect × 0.11` and an upper cap of `Intellect × 0.55`

The scaling formula doesn't mention level, but if we assume the level is just a flat bonus, that's an additional flat 24.5 at 70.

![image](https://user-images.githubusercontent.com/7716908/93671464-ceb91400-fa68-11ea-8d16-d2c0fc88d925.png)
![Zero Mana](https://user-images.githubusercontent.com/7716908/93671319-a250c800-fa67-11ea-956c-90f2ff9e43b5.jpg)
![Full Mana](https://user-images.githubusercontent.com/7716908/93671332-aa106c80-fa67-11ea-8c75-655c55d881f0.jpg)
Note that I have zero MP5 from gear or talents; my MP5 without Viper on is zero.

**Server Revision**: 
3531

**Comment by Wolffenstein** [comment]
Fixed in rev 3532.

**Comment by raethkcj** [comment]
@Wolffenstein I didn't get around to confirming this fix until now. For some reason, it seems like Viper was actually *buffed*? My interpretation of the formula above is that my MP5 from Viper should be calculated like this:

```
function viper_mp5(intellect, mana_current, mana_max, level) {
    let mana_percent = mana_current / mana_max
    let intellect_regen = intellect * 22/35 * (0.9 - mana_percent) + intellect * 0.11
    
    // Cap the regen between the min and max
    let intellect_min = intellect * 0.11
    let intellect_max = intellect * 0.55
    intellect_regen = Math.max(intellect_regen, intellect_min)
    intellect_regen = Math.min(intellect_regen, intellect_max)
    
    let level_regen = 0.35 * level
    
    return intellect_regen + level_regen
}
```

Using the inputs from my character below, this gives me:

```
console.log(viper_mp5(82, 4333, 4333, 70))
> 33.5199999999996
```

But in-game, I'm still getting 165 mp5.

![image](https://user-images.githubusercontent.com/7716908/99560636-b3e11e00-298b-11eb-9b9a-081eaab98ce8.png)
