### ISSUE TITLE
[NPC]Marsh Murloc

### ISSUE THREAD

**Issue by Rickybobby90** [Atlantiss/NetherwingBugtracker#824]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: The quest, Threat From the Sea, is unable to be complete due to lack of mobs.

**Current behaviour**: Marsh Murloc seem to be replaced with Marsh Flesheater on the coast of Swamp of Sorrows.

**Expected behaviour**: Marsh Murloc should populate the coastline.

**Server Revision**: 2079

**Comment by Rickybobby90** [comment]
http://db.excalibur.ws/?npc=747

**Comment by aresbrutus** [comment]
Some issue with shared spawn pools, need to check groups, locations and what makes them not spawn.

**Comment by Kidcudi123** [comment]
Damn

**Comment by aresbrutus** [comment]
Should be fixed in one of the next updates. Please re-check.

**Comment by DemonHunter1992** [comment]
update, not fixed

**Comment by aresbrutus** [comment]
Already known at https://github.com/Atlantiss/NetherwingBugtracker/issues/1433

**Comment by femtaur** [comment]
still not #fixedwing

**Comment by Cinx787** [comment]
still not fixed and the issue was brought up in October during the beta
